server:
  port: 9003
spring:
  application:
    name: eureka-server
    # 单机版配置
eureka:
  client:
    fetch-registry: false # 是否需要从Eureka获取注册信息
    register-with-eureka: false # 是否需要把该服务注册到Eureka
    service-url:  # 暴露Eureka注册地址
      defaultZone: http://127.0.0.1:${server.port}/eureka
  server:
    #修改扫描失效服务间隔时间
    #eviction-interval-timer-in-ms: 5000
    #取消自我保护机制
    enable-self-preservation: false



    #集群配置

#eureka:
#  client:
#    fetch-registry: true # 是否需要从Eureka获取注册信息
#    register-with-eureka: true # 是否需要把该服务注册到Eureka
#    service-url:  # 暴露Eureka注册地址
#      defaultZone: http://127.0.0.1:9003/eureka